/**
 * The app-owned Tauri command surface.
 *
 * Specta's DataError mode generates the Wellcrafted-compatible `{ data, error }`
 * shape for fallible commands. Infallible commands keep their generated return
 * type. This file provides the hand-rolled command for raw byte traffic
 * (`encodeRecordingForUpload`). The Rust side returns
 * `tauri::ipc::Response::new(opus_bytes)` for upload-cost reasons;
 * tauri-specta cannot generate a typed binding for that shape because
 * `Response` is not `specta::Type`. The handwritten wrapper here is the
 * full TS-side contract: future commands that need raw bytes follow the
 * same pattern.
 *
 * **Import discipline**: this is the only file in `src/lib/**` that imports
 * from `@tauri-apps/api/core` for app-owned commands. Tauri plugin APIs
 * (fs, clipboard, etc.) keep their own imports.
 */

import type { BlobDestination } from '@epicenter/blobs/native';
import { invoke as rawInvoke } from '@tauri-apps/api/core';
import { Err, Ok, type Result } from 'wellcrafted/result';
import { events, commands as gen } from './bindings.gen';

/**
 * Hand-rolled raw-byte command outside the generated surface. The Rust
 * return is a raw IPC byte body (`tauri::ipc::Response::new(opus_bytes)`).
 * The success type is therefore `ArrayBuffer` rather than a serialized
 * struct. Error path is a plain string from Tauri's reject channel.
 */
async function encodeRecordingForUpload(
	audioBlobId: string,
	destination: BlobDestination,
): Promise<Result<ArrayBuffer, string>> {
	try {
		return Ok(
			await rawInvoke<ArrayBuffer>('encode_recording_for_upload', {
				audioBlobId,
				destination,
			}),
		);
	} catch (e) {
		return Err(String(e));
	}
}

export const commands = {
	...gen,
	encodeRecordingForUpload,
};

export type {
	DeviceAcquisition,
	DictationCapability,
	EndedReason,
	GlobalShortcutRegistration,
	HostRecording,
	LocalTranscriptionReadiness,
	MicrophonePermission,
	RecorderError as IpcRecorderError,
	StoppedRecording,
	TranscriptionError,
	TranscriptionHints,
	TranscriptionOutcome,
} from './bindings.gen';
/**
 * Typed event listeners generated by tauri-specta. Each leaf
 * (`events.dictationCapabilityEvent`) binds the topic name to its payload type,
 * so call sites listen without hand-mirroring the Rust topic string. Re-exported
 * raw: events carry plain payloads, so there is no `Result` shape to convert.
 */
export { events };
